# Generated by Django 6.0.4 on 2026-04-24 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="insurance_remark",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prescription",
            name="refills_left",
            field=models.IntegerField(default=0),
        ),
    ]
