# Generated by Django 6.0.4 on 2026-04-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_prescription_insurance_remark_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="sig",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
