# Generated by Django 6.0.4 on 2026-04-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_prescription_sig"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="quantity",
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="last_filled_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="next_fill_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="rx_number",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
