# Generated by Django 6.0.4 on 2026-04-28 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_prescription_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="otmalert",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_alerts",
                to="core.patient",
            ),
        ),
        migrations.AlterField(
            model_name="otmalert",
            name="prescription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="core.prescription",
            ),
        ),
    ]
